import {
  createAccountPath,
  createEventPath,
  createEventsPath,
  createGamePath,
  createGamesPath,
  createHomePath,
  createNewGamePath,
  createPlayerPath,
  createPlayersPath,
  createPlayPath,
  createPlaysPath,
  createSettingsPath,
  createSignInPath,
  createSignUpPath,
  createToolPath,
  createToolsPath,
} from './pathCreators';
import Path, { RouteAccess } from './enums';
import AnimatedRoutes from './AnimatedRoutes';

export {
  AnimatedRoutes,
  createAccountPath,
  createEventsPath,
  createEventPath,
  createGamesPath,
  createGamePath,
  createHomePath,
  createNewGamePath,
  createPlayersPath,
  createPlayerPath,
  createPlaysPath,
  createPlayPath,
  createSettingsPath,
  createSignInPath,
  createSignUpPath,
  createToolsPath,
  createToolPath,
  Path,
  RouteAccess,
};
