export default {
  ACCESS_PRIVATE_KEY: '',
  ACCESS_PUBLIC_KEY: '',
  ACCESS_TOKEN_EXP: 900,
  APP_NAME: 'Handle It',
  CLIENT_HOST: 'localhost:4000',
  COMPANY_ADDRESS: 'street,_city,_country',
  COMPANY_EMAIL: 'company@name.com',
  COMPANY_NAME: 'Company Name',
  COMPANY_PHONE: '_00_000_000_000',
  CONFIRM_SIGN_UP_TOKEN_EXP: 86400,
  HOST: 'localhost:5000',
  NODE_ENV: 'test',
  PORT: 5000,
  PROTOCOL: 'http://',
  REFRESH_PRIVATE_KEY: '',
  REFRESH_PUBLIC_KEY: '',
  REFRESH_TOKEN_EXP: 604800,
  REMOVE_ACCOUNT_TOKEN_EXP: 3600,
  RESET_PASSWORD_TOKEN_EXP: 3600,
  SENDER_EMAIL: 'test@example.com',
  SENDGRID_API_KEY: 'sendgrid_api_key',
  TOKEN_PRIVATE_KEY: '',
  TOKEN_PUBLIC_KEY: '',
};
